# This is a basic workflow that is manually triggered

name: Palette Generator

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  generate:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - uses: actions/setup-python@v4
      with:
        python-version: '3.11' 
    
    - run: python -m pip install lief frida frida-tools
    
    - name: Download BDS
      shell: bash
      run: |
        SERVER="https://minecraft.azureedge.net/bin-linux/bedrock-server-1.19.50.02.zip"
        mkdir -p bds
        cd bds
        curl $SERVER -o serverpack.zip
        unzip -q serverpack.zip
        
    - name: Clone devkit
      uses: actions/checkout@v3
      with:
        repository: 'pmmp/bds-modding-devkit'
        submodules: 'recursive'
        
    - name: Setup modded server
      shell: bash
      run: |
        ./scripts/setup ~/bds

